MvcStok/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcStok.Models.Entity;//Şayet bu modeli tanıtmazsam çalışmaz.

namespace MvcStok.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        MvcDbStokEntities1 db=new MvcDbStokEntities1(); //Tablolara ulaşmak için db nesnesi türetiyorum.
        //Bu benim modelimi tutuyor. Modelimde de tablolarım var.
        public ActionResult Index()
        {
            var degerler=db.TBLKATEGORILER.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View(); //Sayfa çağrıldıgında sadece view getirsin. yoksa her sayfa açıldıgında kategori ekler.
            //Thats why we use httpget and httppost. these are different things..
        }


        [HttpPost] //Butona tıkladıgımda çalışacak.
        public ActionResult YeniKategori(TBLKATEGORILER p1) //Kategori ekleme için böyle bir şey yaptım. parametre1
        {
            db.TBLKATEGORILER.Add(p1); //Gelen parametreyi tbl kategorilere ekle
            db.SaveChanges();
            return View();
        }

        public ActionResult SIL(int id) //Silme işlemi için id değişkeni tanımladım. ID'ye göre sildireceğim.
        {
            var kategori=db.TBLKATEGORILER.Find(id); //TBLKAtegorilerde bul neyi bul id'den gelen değeri bul.
            db.TBLKATEGORILER.Remove(kategori);//TBLKAtegorilerdeki değeri sil neyi sil kategori değişkeninden geleni.
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GUNCELLE(int id)
        {
            var ktgr = db.TBLKATEGORILER.Find(id);
            return View("KategoriGetir",ktgr);
        }
    }
}

MvcStok/Views/Kategori/Index.cshtml
@using MvcStok.Models.Entity
@model List<TBLKATEGORILER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>KATEGORİ ID</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr><!-- tr table row demek-->
    <tbody>
        @foreach (var item in Model) //Buradaki Modeli yulkarıdaki @model'den geliyor.
        {
        <tr>
            <th>@item.KATEGORIID</th><!--td table data demek. ince olur. th kalındr.-->
            <td>@item.KATEGORIAD</td>
            <td><a href="/KATEGORI/SIL/@item.KATEGORIID" class="btn btn-danger">SİL</a></td>
            <td><a href="/KATEGORI/GUNCELLE/@item.KATEGORIID" class="btn btn-success" >GÜNCELLE</a></td>
        </tr>

        }
    </tbody>
</table>
<a href="/KATEGORI/YeniKategori/" class="btn btn-primary">YENİ KATEGORİ EKLE</a>

MvcStok/Views/Kategori/KategoriGetir.cshtml
@model MvcStok.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "GUNCELLE";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Kategori", FormMethod.Post))
{
    //Bu formda bir action oldugu zaman güncelleyi çalıştıracak.
    //Guncelle nerede? Kategoride. Ne zaman çalışacak form method mpost oldugunda.

<div class="form-group">
    @Html.LabelFor(m => m.KATEGORIID)
    @Html.TextBoxFor(m => m.KATEGORIID, new { @class = "form-control" })

    @Html.LabelFor(m => m.KATEGORIAD)
    @Html.TextBoxFor(m => m.KATEGORIAD, new { @class="form-control" })
</div>
}

MvcStok/Views/Kategori/YeniKategori.cshtml
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post"> <!-- Form butona tıkladıgımda işleyecek, post işlemi oldugunda yani-->
    <div>
        <label>Kategori Adı</label>
        <input type="text" class="form-control" name="KATEGORIAD" />
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>
</form>